package formularios;

import implementaciones.DAOSFactory;
import interfaces.IClientesDAO;
import interfaces.IProductosDAO;
import interfaces.IRelacionProductosVentasDAO;
import interfaces.IVentasDAO;

/**
 * Form del menu.
 *
 * @author Luis Gonzalo y José Jesús
 */
public class MenuForm extends javax.swing.JFrame {

    /**
     * Clientes DAO.
     */
    private final IClientesDAO clienteDAO;
    /**
     * Productos DAO
     */
    private final IProductosDAO productoDAO;
    /**
     * Ventas DAO
     */
    private final IVentasDAO ventasDAO;
    /**
     * Relaciones DAO
     */
    private final IRelacionProductosVentasDAO rpvDAO;

    /**
     * Creates new form MenuForm
     */
    public MenuForm() {
        initComponents();
        this.clienteDAO = DAOSFactory.crearClientesDAO();
        this.ventasDAO = DAOSFactory.crearVentasDAO();
        this.productoDAO = DAOSFactory.crearProductosDAO();
        this.rpvDAO = DAOSFactory.crearRelacionProductosVentasDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelClientes = new javax.swing.JPanel();
        jLabelClientes = new javax.swing.JLabel();
        jButtonClientes = new javax.swing.JButton();
        jPanelProductos = new javax.swing.JPanel();
        jLabelProductos = new javax.swing.JLabel();
        jButtonProductos = new javax.swing.JButton();
        jPanelVentas = new javax.swing.JPanel();
        jLabelVentas = new javax.swing.JLabel();
        jButtonVentas = new javax.swing.JButton();
        jPanelBsuquedas = new javax.swing.JPanel();
        jLabelBusquedas = new javax.swing.JLabel();
        jButtonBusquedas = new javax.swing.JButton();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelLinea1 = new javax.swing.JPanel();
        jPanelLinea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú");
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelClientes.setBackground(new java.awt.Color(255, 255, 255));
        jPanelClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelClientes.setLayout(null);

        jLabelClientes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClientes.setText("Clientes");
        jPanelClientes.add(jLabelClientes);
        jLabelClientes.setBounds(50, 40, 100, 40);

        jButtonClientes.setBackground(new java.awt.Color(255, 255, 255));
        jButtonClientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonClientes.setText("Entrar");
        jButtonClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });
        jPanelClientes.add(jButtonClientes);
        jButtonClientes.setBounds(60, 250, 80, 30);

        getContentPane().add(jPanelClientes);
        jPanelClientes.setBounds(210, 90, 190, 350);

        jPanelProductos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelProductos.setLayout(null);

        jLabelProductos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelProductos.setText("Productos");
        jPanelProductos.add(jLabelProductos);
        jLabelProductos.setBounds(30, 40, 130, 40);

        jButtonProductos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonProductos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonProductos.setText("Entrar");
        jButtonProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductosActionPerformed(evt);
            }
        });
        jPanelProductos.add(jButtonProductos);
        jButtonProductos.setBounds(50, 250, 80, 30);

        getContentPane().add(jPanelProductos);
        jPanelProductos.setBounds(10, 90, 200, 350);

        jPanelVentas.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelVentas.setLayout(null);

        jLabelVentas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelVentas.setText("Ventas");
        jPanelVentas.add(jLabelVentas);
        jLabelVentas.setBounds(60, 40, 90, 40);

        jButtonVentas.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVentas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonVentas.setText("Entrar");
        jButtonVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVentasActionPerformed(evt);
            }
        });
        jPanelVentas.add(jButtonVentas);
        jButtonVentas.setBounds(60, 250, 80, 30);

        getContentPane().add(jPanelVentas);
        jPanelVentas.setBounds(590, 90, 190, 350);

        jPanelBsuquedas.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBsuquedas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelBsuquedas.setLayout(null);

        jLabelBusquedas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelBusquedas.setText("Búsquedas");
        jPanelBsuquedas.add(jLabelBusquedas);
        jLabelBusquedas.setBounds(40, 40, 130, 40);

        jButtonBusquedas.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBusquedas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBusquedas.setText("Entrar");
        jButtonBusquedas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonBusquedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusquedasActionPerformed(evt);
            }
        });
        jPanelBsuquedas.add(jButtonBusquedas);
        jButtonBusquedas.setBounds(60, 250, 80, 30);

        getContentPane().add(jPanelBsuquedas);
        jPanelBsuquedas.setBounds(400, 90, 190, 350);

        jPanelTitulo.setBackground(new java.awt.Color(153, 255, 255));
        jPanelTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelTitulo.setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelTitulo.setText("Punto de Ventas");
        jPanelTitulo.add(jLabelTitulo);
        jLabelTitulo.setBounds(240, 20, 320, 40);

        jPanelLinea1.setBackground(new java.awt.Color(0, 0, 0));
        jPanelLinea1.setLayout(null);
        jPanelTitulo.add(jPanelLinea1);
        jPanelLinea1.setBounds(780, 90, 20, 350);

        jPanelLinea.setBackground(new java.awt.Color(0, 0, 0));
        jPanelLinea.setLayout(null);
        jPanelTitulo.add(jPanelLinea);
        jPanelLinea.setBounds(0, 90, 20, 350);

        getContentPane().add(jPanelTitulo);
        jPanelTitulo.setBounds(0, 0, 800, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
     * Evento del boton productos, que inicializa el form de productos.
     *
     * @param evt Evento.
     */
    private void jButtonProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductosActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ProductosForm(productoDAO).setVisible(true);
            }
        });
    }//GEN-LAST:event_jButtonProductosActionPerformed
    /**
     * Evento del boton clientes, que inicializa el form de clientes.
     *
     * @param evt Evento.
     */
    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ClientesForm(clienteDAO).setVisible(true);
            }
        });
    }//GEN-LAST:event_jButtonClientesActionPerformed
    /**
     * Evento del boton busquedas, que inicializa el form busqeudas.
     *
     * @param evt Evento.
     */
    private void jButtonBusquedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusquedasActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BusquedaVentasForm(ventasDAO, clienteDAO, rpvDAO).setVisible(true);
            }
        });
    }//GEN-LAST:event_jButtonBusquedasActionPerformed
    /**
     * Evento del boton ventas, que inicializa el form de ventas.
     *
     * @param evt Evento.
     */
    private void jButtonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVentasActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RegistroVentasForm(ventasDAO, productoDAO, clienteDAO, rpvDAO).setVisible(true);
            }
        });    }//GEN-LAST:event_jButtonVentasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBusquedas;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonProductos;
    private javax.swing.JButton jButtonVentas;
    private javax.swing.JLabel jLabelBusquedas;
    private javax.swing.JLabel jLabelClientes;
    private javax.swing.JLabel jLabelProductos;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelVentas;
    private javax.swing.JPanel jPanelBsuquedas;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JPanel jPanelLinea;
    private javax.swing.JPanel jPanelLinea1;
    private javax.swing.JPanel jPanelProductos;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JPanel jPanelVentas;
    // End of variables declaration//GEN-END:variables
}
