package guis;

import entidades.Lugar;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.ILugarDAO;

/**
 * Form de lugares.
 *
 * @author José Jesús Orozco Hernández ID; 00000229141
 */
public class LugaresForm extends javax.swing.JFrame {

    /**
     * Conexion a lugarDAO
     */
    private final ILugarDAO lugarDAO;

    /**
     * Constructor de lugarDAO.
     *
     * @param lugarDAO Conexion a lugarDAO
     */
    public LugaresForm(ILugarDAO lugarDAO) {
        initComponents();
        this.lugarDAO = lugarDAO;
        this.llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLongitud = new javax.swing.JLabel();
        jTextFieldIDLugar = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldBuscarID = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        tablaSocios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLugares = new javax.swing.JTable();
        jButtonBuscar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jLabelIDLugar = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldLongitud = new javax.swing.JTextField();
        jButtonEditar = new javax.swing.JButton();
        jLabelLatitud = new javax.swing.JLabel();
        jTextFieldLatitud = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administracion de Lugares");
        setMaximumSize(new java.awt.Dimension(900, 400));
        setMinimumSize(new java.awt.Dimension(900, 400));
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        jLabelLongitud.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelLongitud.setText("Longitud;");
        getContentPane().add(jLabelLongitud);
        jLabelLongitud.setBounds(20, 230, 100, 30);

        jTextFieldIDLugar.setEditable(false);
        getContentPane().add(jTextFieldIDLugar);
        jTextFieldIDLugar.setBounds(130, 20, 80, 30);
        getContentPane().add(jTextFieldNombre);
        jTextFieldNombre.setBounds(130, 80, 150, 30);
        getContentPane().add(jTextFieldBuscarID);
        jTextFieldBuscarID.setBounds(290, 20, 350, 30);

        jButtonGuardar.setBackground(new java.awt.Color(0, 255, 255));
        jButtonGuardar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardar);
        jButtonGuardar.setBounds(20, 290, 120, 40);

        jButtonCancelar.setBackground(new java.awt.Color(51, 255, 255));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(160, 290, 120, 40);

        jTableLugares.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableLugares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Lugar", "Nombre", "Dirección", "Latitud", "Longitud"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLugares.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableLugares);

        tablaSocios.add(jScrollPane1);

        getContentPane().add(tablaSocios);
        tablaSocios.setBounds(290, 70, 450, 290);

        jButtonBuscar.setBackground(new java.awt.Color(102, 255, 255));
        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar);
        jButtonBuscar.setBounds(640, 20, 100, 30);

        jButtonEliminar.setBackground(new java.awt.Color(102, 255, 255));
        jButtonEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar);
        jButtonEliminar.setBounds(760, 130, 100, 30);

        jLabelIDLugar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelIDLugar.setText("ID Lugar;");
        getContentPane().add(jLabelIDLugar);
        jLabelIDLugar.setBounds(20, 20, 100, 30);

        jLabelNombre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelNombre.setText("Nombre;");
        getContentPane().add(jLabelNombre);
        jLabelNombre.setBounds(20, 80, 90, 30);

        jLabelDireccion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelDireccion.setText("Dirección;");
        getContentPane().add(jLabelDireccion);
        jLabelDireccion.setBounds(20, 130, 100, 30);
        getContentPane().add(jTextFieldDireccion);
        jTextFieldDireccion.setBounds(130, 130, 150, 30);
        getContentPane().add(jTextFieldLongitud);
        jTextFieldLongitud.setBounds(130, 230, 150, 30);

        jButtonEditar.setBackground(new java.awt.Color(102, 255, 255));
        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(760, 80, 100, 30);

        jLabelLatitud.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelLatitud.setText("Latitud;");
        getContentPane().add(jLabelLatitud);
        jLabelLatitud.setBounds(20, 180, 100, 30);
        getContentPane().add(jTextFieldLatitud);
        jTextFieldLatitud.setBounds(130, 180, 150, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
     * Evento del boton guardar que sucede cuando el usuario da click.
     *
     * @param evt Evento
     */
    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        this.guardar();
    }//GEN-LAST:event_jButtonGuardarActionPerformed
    /**
     * Evento del boton cancelar que sucede cuando el usuario da click.
     *
     * @param evt Evento
     */
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.limpiar();
    }//GEN-LAST:event_jButtonCancelarActionPerformed
    /**
     * Evento del boton buscar que sucede cuando el usuario da click.
     *
     * @param evt Evento
     */
    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        this.buscar();
    }//GEN-LAST:event_jButtonBuscarActionPerformed
    /**
     * Evento del boton editar que sucede cuando el usuario da click.
     *
     * @param evt Evento
     */
    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        this.editar();
    }//GEN-LAST:event_jButtonEditarActionPerformed
    /**
     * Evento del boton eliminar que sucede cuando el usuario da click.
     *
     * @param evt Evento
     */
    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        this.eliminar();
    }//GEN-LAST:event_jButtonEliminarActionPerformed
    /**
     * Metodo que busca un lugar y rellena los datos.
     */
    private void buscar() {
        if (jTextFieldBuscarID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se pudo buscar el lugar",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String numero = jTextFieldBuscarID.getText();
            if (!validaEntero(numero)) {
                JOptionPane.showMessageDialog(this, "Porfavor solo escriba numeros el id del lugar es un numero",
                        "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (numero.length() > 10) {
                    JOptionPane.showMessageDialog(this, "El maximo numero permitido de caracteres es 10, ejemplo 1234567890",
                            "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    Lugar lugar = this.lugarDAO.consultar(Integer.valueOf(numero));
                    if (lugar != null) {
                        this.llenarFormulario(lugar);
                    }
                }
            }
        }
        this.jTextFieldBuscarID.setText("");
    }

    /**
     * Metodo que guarda o actualiza un lugar.
     */
    private void guardar() {
        if (this.jTextFieldIDLugar.getText().isEmpty()) {
            this.agregar();
        } else {
            this.actualizar();
        }
    }

    /**
     * Metodo que actualiza un lugar
     */
    private void actualizar() {
        Integer idLugar = Integer.valueOf(this.jTextFieldIDLugar.getText());
        //Verificar todos los datos
        if (this.verificarDatosVacios()) {
            return;
        }

        if (this.verificarCantidadTamanho()) {
            return;
        }

        if (this.vericarDobles()) {
            return;
        }

        if (this.vericarDoblesTamaños()) {
            return;
        }
        
        String nombre = this.jTextFieldNombre.getText();
        String direccion = this.jTextFieldDireccion.getText();
        Float latitud = Float.valueOf(this.jTextFieldLatitud.getText());
        Float longitud = Float.valueOf(this.jTextFieldLongitud.getText());
        Lugar lugar = new Lugar(idLugar, nombre, direccion, latitud, longitud);
        boolean seActualizoLugar = this.lugarDAO.actualizar(lugar);
        if (seActualizoLugar) {
            JOptionPane.showMessageDialog(this, "Se actualizo el lugar",
                    "Informacion", JOptionPane.INFORMATION_MESSAGE);
            this.limpiar();
            this.llenarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar el lugar",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Metodo que valida si la cadena es un entero.
     *
     * @param s La cadena a evaluar
     * @return true si es entero, false en caso contrario
     */
    private boolean validaEntero(String s) {
        CharSequence cadena = s.trim();
        String reCadena = "^\\d+$";
        Pattern pattern = Pattern.compile(reCadena);
        Matcher matcher = pattern.matcher(cadena);
        return matcher.matches();
    }

    /**
     * Metodo que valida si la cadena es doble.
     *
     * @param s La cadena a evaluar
     * @return true si es entero, false en caso contrario
     */
    private boolean validarDobles(String as) {
        CharSequence cadena = as.trim();
        String reCadena = "^[0-9]+([.][0-9]+)?$";
        Pattern pattern = Pattern.compile(reCadena);
        Matcher matcher = pattern.matcher(cadena);
        return matcher.matches();
    }

    /**
     * Metodo que evalua si los campos de texto nombre,dirección, latitud y
     * longitud no estan vacios.
     *
     * @return true si estos no cumplen, false en caso contrario
     */
    private boolean verificarDatosVacios() {
        if (jTextFieldNombre.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Es necesario escribir el nombre antes de guardar/actualizar.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return true;
        }
        if (jTextFieldDireccion.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Es necesario escribir la direccion antes de guardar/actualizar.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return true;
        }
        if (jTextFieldLatitud.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Es necesario escribir la latitud antes de guardar/actualizar.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return true;
        }
        if (jTextFieldLongitud.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Es necesario escribir la longitud antes de guardar/actualizar.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return true;
        }
        return false;
    }

    /**
     * Metodo que verifica si la latitud o longitud son dobles.
     *
     * @return true si no lo son, false en caso contrario
     */
    private boolean vericarDobles() {
        String latitud = this.jTextFieldLatitud.getText();
        String longitud = this.jTextFieldLongitud.getText();
        if (!this.validarDobles(latitud)) {
            JOptionPane.showMessageDialog(this, "Es necesario escribir valores dobles(Ejemplo 1.2) la latitud es un numero.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return true;
        }
        if (!this.validarDobles(longitud)) {
            JOptionPane.showMessageDialog(this, "Es necesario escribir valores dobles(Ejemplo 1.2) la longitud es un numero.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return true;
        }
        return false;
    }

    /**
     * Metodo que verifica si la latitud o longitud no sobrepasn un limite de
     * caracteres.
     *
     * @return true si los pasan,false en caso contrario
     */
    private boolean vericarDoblesTamaños() {
        String latitud = this.jTextFieldLatitud.getText();
        String longitud = this.jTextFieldLongitud.getText();
        if (latitud.length() > 7) {
            JOptionPane.showMessageDialog(this, "El maximo numero de caracteres permitidos en la latitud es de 7 ejemplo; 123456.7 o 12345.67",
                    "Error Tamaño", JOptionPane.ERROR_MESSAGE);
            return true;
        }
        if (longitud.length() > 7) {
            JOptionPane.showMessageDialog(this, "El maximo numero de caracteres permitidos en la longitud es de 7 ejemplo; 123456.7 o 12345.67",
                    "Error Tamaño", JOptionPane.ERROR_MESSAGE);
            return true;
        }
        return false;
    }

    /**
     * Metodo que verifica si los campo de texto nombre y dirección sobrepasan
     * un tamaño limite
     *
     * @return true si estos no cumplen, false en caso contrario
     */
    private boolean verificarCantidadTamanho() {
        String nombre = this.jTextFieldNombre.getText();
        String direccion = this.jTextFieldDireccion.getText();
        if (nombre.length() > 100) {
            JOptionPane.showMessageDialog(this, "El nombre es demasiado largo, maximo 100 caracteres.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return true;
        }
        if (direccion.length() > 200) {
            JOptionPane.showMessageDialog(this, "La direccion es demasiada larga, maximo 200 caracteres.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return true;
        }

        return false;
    }

    /**
     * Metodo que agrega un lugar
     */
    private void agregar() {
        if (this.verificarDatosVacios()) {
            return;
        }

        if (this.verificarCantidadTamanho()) {
            return;
        }

        if (this.vericarDobles()) {
            return;
        }

        if (this.vericarDoblesTamaños()) {
            return;
        }

        String nombre = this.jTextFieldNombre.getText();
        String direccion = this.jTextFieldDireccion.getText();
        Float latitud = Float.valueOf(this.jTextFieldLatitud.getText());
        Float longitud = Float.valueOf(this.jTextFieldLongitud.getText());
        Lugar lugar = new Lugar(nombre, direccion, latitud, longitud);
        boolean seAgregoLugar = this.lugarDAO.agregar(lugar);
        if (seAgregoLugar) {
            JOptionPane.showMessageDialog(this, "Se agrego el lugar",
                    "Informacion", JOptionPane.INFORMATION_MESSAGE);
            this.limpiar();
            this.llenarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo agregar el lugar",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Metodo que llena los datos del lugar en los campos de texto
     * correspondientes
     *
     * @param lugar Lugar
     */
    private void llenarFormulario(Lugar lugar) {
        this.jTextFieldIDLugar.setText(String.valueOf(lugar.getIdLugar()));
        this.jTextFieldNombre.setText(lugar.getNombre());
        this.jTextFieldDireccion.setText(lugar.getDireccion());
        this.jTextFieldLatitud.setText(String.valueOf(lugar.getLatitud()));
        this.jTextFieldLongitud.setText(String.valueOf(lugar.getLongitd()));
    }

    /**
     * Metodo que limpia todos los campos de texto.
     */
    private void limpiar() {
        this.jTextFieldIDLugar.setText("");
        this.jTextFieldNombre.setText("");
        this.jTextFieldDireccion.setText("");
        this.jTextFieldLatitud.setText("");
        this.jTextFieldLongitud.setText("");
        this.jTextFieldBuscarID.setText("");
    }

    /**
     * Metodo que actualiza un lugar
     */
    private void editar() {
        Integer idLugarEditar = this.getIdLugarSeleccionado();
        if (idLugarEditar == null) {
            JOptionPane.showMessageDialog(this, "Debes de seleccionar un lugar para poder editarlo",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Lugar lugar = this.lugarDAO.consultar(idLugarEditar);
        if (lugar != null) {
            this.llenarFormulario(lugar);
        }
    }

    /**
     * Metodo que elimina un lugar
     */
    private void eliminar() {
        Integer idLugarEliminar = this.getIdLugarSeleccionado();
        if (idLugarEliminar == null) {
            JOptionPane.showMessageDialog(this, "Debes de seleccionar un lugar para eliminarlo",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int opcionSelecionada = JOptionPane.showConfirmDialog(this, "Estas Seguro de eliminar el lugar", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (opcionSelecionada == JOptionPane.NO_OPTION) {
            return;
        }
        boolean seEliminoLugar = this.lugarDAO.eliminar(idLugarEliminar);
        if (seEliminoLugar) {
            JOptionPane.showMessageDialog(this, "Se elimino el lugar",
                    "Informacion", JOptionPane.INFORMATION_MESSAGE);
            this.llenarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar el lugar, este esta relacionado con un evento"
                    + "porfavor si desea eliminarl el lugar elimine el evento",
                    "Error de eliminar", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Metodo para obtener el ID del lugar seleccionado
     *
     * @return El ID obtenido
     */
    private Integer getIdLugarSeleccionado() {
        int indiceFilaSe = this.jTableLugares.getSelectedRow();
        if (indiceFilaSe != -1) {
            DefaultTableModel modeloTabla = (DefaultTableModel) this.jTableLugares.getModel();
            int indiceColumna = 0;
            Integer id = (Integer) modeloTabla.getValueAt(indiceFilaSe, indiceColumna);
            return id;
        } else {
            return null;
        }
    }

    /**
     * Metodo para llenar la tabla con todos los lugares de la base de datos.
     */
    private void llenarTabla() {
        List<Lugar> listaLugares = this.lugarDAO.consultarTodos();
        DefaultTableModel modeloTabla = (DefaultTableModel) this.jTableLugares.getModel();
        modeloTabla.setRowCount(0);
        listaLugares.forEach(lugar -> {
            Object[] fila = new Object[5];
            fila[0] = lugar.getIdLugar();
            fila[1] = lugar.getNombre();
            fila[2] = lugar.getDireccion();
            fila[3] = lugar.getLatitud();
            fila[4] = lugar.getLongitd();
            modeloTabla.addRow(fila);
        }
        );

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelIDLugar;
    private javax.swing.JLabel jLabelLatitud;
    private javax.swing.JLabel jLabelLongitud;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLugares;
    private javax.swing.JTextField jTextFieldBuscarID;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldIDLugar;
    private javax.swing.JTextField jTextFieldLatitud;
    private javax.swing.JTextField jTextFieldLongitud;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JPanel tablaSocios;
    // End of variables declaration//GEN-END:variables
}
